#pragma once

enum class Status
{
	READY,
	TOO_MANY_ARGUMENTS,
	TOO_FEW_ARGUMENTS,
	NO_DIRECTORY_PATH_FOUND,
	INVALID_PERMISSIONS_DIRECTORY_MOVE,
	PATH_MISSING,
	INVALID_PERMISSIONS_DIRECTORY_CREATE,
	CREATION_FAILED
};